[project]
name = "multi-module"
version = "0.1.0"
edition = "2026"
requires-arx = ">=1.0"

[build-system]
dependencies = [
  "arxlang>=1.0",
]

[build]
src_dir = "src"
out_dir = "build"
package = "multi_module"
mode = "app"
