[project]
name = "local-consumer"
version = "0.1.0"
edition = "2026"

dependencies = [
  "local_lib @ ../local_lib",
  "pyyaml",
]

[build]
src_dir = "src"
entry = "main.x"
out_dir = "build"

[toolchain]
compiler = "arx"
linker = "clang"
